### ISSUE TITLE
Dungeon List has issue parsing commas.

### ISSUE THREAD

**Issue by lugielord** [amoeba/acdungeonmaps#4]
https://[dungeonmaps.treestats.net](https://dungeonmaps.treestats.net/)/

The webpage seems to have issues parsing commas.  

I see issues with the following 5 dungeons.

Secret Chamber of Kresovus (Part1: Trials of the Arm, Mind and Heart) 0x009F
Temple of the Three, Ritual Chambers 0x00E4
Roots of Skuld, Urd and Verdandi 0x24C0
Catacombs (20.5S, 7.6E) 0x5754
Mysterious Hatch (77.9N, 42.5W) 0x654C

Other than that it is a very helpful list of AC Dungeons. 
Thank you!

**Comment by amoeba** [comment]
Hi @lugielord, thanks for the bug report. You're totally right that something is messed up. I'll push up a fix in a bit here.

**Comment by amoeba** [comment]
@lugielord let me know if the above things aren't fixed. Thanks again for the report.

**Comment by lugielord** [comment]
Looks great!  Thanks for taking the time to make this update!
